apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ps-exporter
  namespace: nc
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: ps-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: ps-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: ps-exporter
    spec:
      containers:
      - name: ps-exporter
        image: nexclipper/ps-exporter:latest
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /host/proc
          mountPropagation: HostToContainer
          name: proc
          readOnly: true
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - hostPath:
          path: /proc
        name: proc
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate