apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: ps-exporter
  name: ps-exporter
  namespace: nc
spec:
  clusterIP: None
  ports:
  - name: tcp
    port: 9095
    targetPort: tcp
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: ps-exporter